### ISSUE TITLE
missing schema

### ISSUE THREAD

**Issue by r3sist** [janfitz/fuelManagement#1]
Hi janfitz!

I like your project's simplicity, I could use it for my own, but I haven't found any schema info. I keep getting
`SQLite3::query(): Unable to prepare statement: 1, no such table: car ...` errors. Could you help me in this?

Thank you!

**Comment by janfitz** [comment]
Hi r3sist,

thank you for your message. In master you can now find two example sqlite databases. Everything should works fine. You can clone the scheme or edit one of included database. It should be enough to pull changes. If some error occured, please let me know.

**Comment by r3sist** [comment]
Works perfect! Thank you for your quick help!
